### ISSUE TITLE
Crashes on the Craft of Exile 2 build

### ISSUE THREAD

**Issue by Psizmo** [Truly-Modular/Arsenal#4]
I understand crashes because of the mod Mine&Slash?
[latest.log](https://github.com/user-attachments/files/16471485/latest.log)

**Comment by Smartin-b** [comment]
what exactly is triggering the crash?
opening the gui?
loading a specific world?
loading any world?

**Comment by Psizmo** [comment]
It's hard to explain the reason for the departure. I'll try to record the crash

**Comment by Psizmo** [comment]
https://youtu.be/ZGyiy7XWo80
[latest.log](https://github.com/user-attachments/files/16471851/latest.log)

This is also sometimes the case with swords. Haven't checked with armor or arrows.

**Comment by Psizmo** [comment]
https://youtu.be/VIXDoJ2ZiWY
[crash-2024-08-02_20.07.41-client.txt](https://github.com/user-attachments/files/16472323/crash-2024-08-02_20.07.41-client.txt)
Tried testing on a clean build with only true modular. and it still crashes. That's weird.

**Comment by Smartin-b** [comment]
1.1.26 is out, this should fix the issue

**Comment by Psizmo** [comment]
I think it's fixed. Thank you so much for your promptness
